apiVersion: apps/v1
kind: Deployment
metadata:
  name: agify-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agify-service
  template:
    metadata:
      labels:
        app: agify-service
    spec:
      containers:
      - name: agify-service-container
        image: erickmayorgar/agify-service:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "200m"
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: agify-service
spec:
  selector:
    app: agify-service
  ports:
    - port: 3002
      targetPort: 3002
