apiVersion: apps/v1
kind: Deployment
metadata:
  name: genderize-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genderize-service
  template:
    metadata:
      labels:
        app: genderize-service
    spec:
      containers:
      - name: genderize-service-container
        image: erickmayorgar/genderize-service:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "200m"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: genderize-service
spec:
  selector:
    app: genderize-service
  ports:
    - port: 3001
      targetPort: 3001