- hosts: produccion
  become: yes
  tasks:
  - name: Instalar Nginx
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: Eliminar la configuración predeterminada de Nginx
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: Copiar la configuración de Nginx para la aplicación
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/sites-available/react_app
    notify: restart nginx

  - name: Habilitar la configuración de la aplicación
    file:
      src: /etc/nginx/sites-available/react_app
      dest: /etc/nginx/sites-enabled/react_app
      state: link
    notify: restart nginx

  - name: Copiar el build de React al servidor
    copy:
      src: /home/erick_mayorga_r/ansibleDespliegue/Practica1SA-201901758/practica1sa-201901758-app/dist
      dest: /var/www/react_app
      mode: '0755'

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted